### ISSUE TITLE
[FR] (feature summary)

### ISSUE THREAD

**Issue by herbstleyd** [Ideagen3d/SapphirePlus-Unified-Firmware#1]
### Is your feature request related to a problem? Please describe.

No SD-Card Support activated

### Are you looking for hardware support?

Sapphire Plus V3

### Describe the feature you want

Can you activate SD-Card support for the "SapphirePLUS-V3-Manual-3x3-Stock-v1.0.11-ColourUI.bin"?

**Comment by slmmnl** [comment]
Sure. We must've missed it out. Check out the latest release for the updated version. Cheers
